obj-$(CONFIG_WIRELESS_CHARGER_S2MIW04)	+= s2miw04_charger.o
obj-$(CONFIG_WIRELESS_CHARGER_CPS4038)	+= cps4038_charger.o
obj-$(CONFIG_WIRELESS_CHARGER_NU1668)   += nu1668_charger.o

ccflags-y := -Wformat
